### ISSUE TITLE
1.21.1-2.1.8.4-beta+8 Crash without KubeJS

### ISSUE THREAD

**Issue by wendall911** [PickAID/Champions#50]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.21.1-2.1.8.4-beta+8
* NeoForge: 21.1.77

#### Steps to Reproduce:
1.
2.
3.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

This template is mostly useless for this bug. I know you are all working on KubeJS support, but is should be an optional package.

**Comment by M1hono** [comment]
It should be fixed now.

**Comment by wendall911** [comment]
This still crashes on the server trying to load a client-side class:

`Champions Unofficial (champions) has failed to load correctly
          java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER`

From the stacktrace:
`
at TRANSFORMER/champions@1.21.1-2.1.8.4-beta+9/top.theillusivec4.champions.Champions.<init>(Champions.java:114) ~[champions-neoforge-1.21.1-2.1.8.4-beta+9.jar%23314!/:?] {re:classloading}
`

This version isn't checked into github, so I can't see the issue.

**Comment by Hypocisy** [comment]
> This still crashes on the server trying to load a client-side class:
> 
> `Champions Unofficial (champions) has failed to load correctly java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER`
> 
> From the stacktrace: `at TRANSFORMER/champions@1.21.1-2.1.8.4-beta+9/top.theillusivec4.champions.Champions.<init>(Champions.java:114) ~[champions-neoforge-1.21.1-2.1.8.4-beta+9.jar%23314!/:?] {re:classloading}`
> 
> This version isn't checked into github, so I can't see the issue.

It has been fixed, and i uploaded beta+10 to CF, you can donwnload it, if you have any issue, you can make a new git issue. thanks!
